--- 
- name: Create admin secutiry group
  vars:
      ansible_python_interpreter: "/var/tmp/venv_shade/bin/python"
  os_security_group:
     validate_certs: no
     cloud: overcloud
     state: present
     name: admin
  delegate_to: "{{ groups.shade | first }}"

- name: Allow any ICMP
  vars:
     ansible_python_interpreter: "/var/tmp/venv_shade/bin/python"
  os_security_group_rule:
     validate_certs: no
     cloud: overcloud
     security_group: admin
     protocol: icmp
     remote_ip_prefix: 0.0.0.0/0
     port_range_min: -1
     port_range_max: -1
  delegate_to: "{{ groups.shade | first }}"

- name: Allow any SSH connection
  vars:
     ansible_python_interpreter: "/var/tmp/venv_shade/bin/python"
  os_security_group_rule:
     validate_certs: no
     cloud: overcloud
     security_group: admin
     protocol: tcp
     port_range_min: 22
     port_range_max: 22
     remote_ip_prefix: 0.0.0.0/0
  delegate_to: "{{ groups.shade | first }}"
