---
- hosts: overcloud_nodes
  tasks:
    - name: Install pcp
      package:
          name: ['pcp']
      become: true
    - name: Start pcp
      shell: |
       service firewalld start
       firewall-cmd --add-port=44321/tcp --permanent
       systemctl start pmcd
       systemctl enable pmcd
      become: true
