---
- name: create clouds.yml
  hosts: undercloud
  tasks:
    - name: get undercloud variables
      shell: |
        for key in $( set | awk '{FS="="}  /^OS_/ {print $1}' ); do unset $key ; done
        source /home/stack/stackrc
        echo -n "undercloud: {'auth': { 'auth_url': '$OS_AUTH_URL', 'username': '$OS_USERNAME', 'password': '$OS_PASSWORD', 'project_name': '${OS_PROJECT_NAME:-$OS_TENANT_NAME}', 'project_domain_name': '$OS_PROJECT_DOMAIN_NAME', 'user_domain_name': '$OS_USER_DOMAIN_NAME'}}"
      register: cloud_details
    - name: create clouds.yaml if doesn't exist
      blockinfile:
          content: 'clouds:'
          dest: /home/stack/clouds.yaml
          marker: "#{mark} HEADER"
          create: yes
    - name: insert undercloud parameters
      blockinfile:
        dest: /home/stack/clouds.yaml
        block: |5
             {{ cloud_details.stdout|from_yaml|to_nice_yaml(indent=4) }}
        insertbefore: "#END undercloud SECTION"
        marker: "#{mark} undercloud PARAMETERS"
    - name: get overcloud variables
      shell: |
          for key in $( set | awk '{FS="="}  /^OS_/ {print $1}' ); do unset $key ; done
          source /home/stack/overcloudrc
          echo -n "overcloud: {'auth': { 'auth_url': '$OS_AUTH_URL', 'username': '$OS_USERNAME', 'password': '$OS_PASSWORD', 'project_name': '${OS_PROJECT_NAME:-$OS_TENANT_NAME}', 'project_domain_name': '$OS_PROJECT_DOMAIN_NAME', 'user_domain_name': '$OS_USER_DOMAIN_NAME' }}"
      register: cloud_details
    - name: create clouds.yaml if doesn't exist
      blockinfile:
        content: 'clouds:'
        dest: /home/stack/clouds.yaml
        marker: "#{mark} HEADER"
        create: yes
    - name: insert overcloud parameters
      blockinfile:
        dest: /home/stack/clouds.yaml
        block: |5
             {{ cloud_details.stdout|from_yaml|to_nice_yaml(indent=4) }}
        insertbefore: "#END overcloud SECTION"
        marker: "#{mark} overcloud PARAMETERS"
