---
- name: Create flavors
  hosts: undercloud
  vars_files:
    - vars/openstack.yml
  tasks:
    - name: Create flavors
      shell: |
        source ~/overcloudrc
        openstack flavor create --vcpus {{ item.cpu }} --disk {{ item.disk }} \
            --ram {{ item.memory }} {{ item.name }}
      with_items: "{{ overcloud_flavors }}"
      ignore_errors: true
    - name: Setup admin quotas
      shell: |
        source ~/overcloudrc
        openstack quota set --properties -1 --server-groups -1 \
            --ram -1 --key-pairs -1 --instances -1 --fixed-ips -1 \
            --injected-file-size -1 --server-group-members -1 \
            --injected-files -1 --cores -1 --injected-path-size -1 \
            --gigabytes -1 --snapshots -1 --volumes -1  --subnetpools -1 \
            --ports -1 --subnets -1  --networks -1 --floating-ips -1 \
            --secgroup-rules -1 --secgroups -1 --routers -1 --rbac-policies -1 admin
      ignore_errors: true
